apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-app-deployment
  labels:
    app: counter-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter-app
  template:
    metadata:
      labels:
        app: counter-app
    spec:
      containers:
        - name: counter-app
          image: gcr.io/sachin-k8s/web-apptwo:latest
          ports:
            - containerPort: 8080
          # Optional: Specify environment variables if needed
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: counter-app-service
spec:
  type: LoadBalancer
  selector:
    app: counter-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
